# Generated by Django 4.1.13 on 2024-10-15 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_amount_income_monthly_income_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
