# Generated by Django 4.1.13 on 2024-10-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_delete_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Bills', 'Bills'), ('Travel', 'Travel'), ('Other', 'Other')], max_length=20),
        ),
    ]
